# Generated by Django 5.1.6 on 2026-03-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_achievement_image_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='category',
            field=models.CharField(choices=[('academic', 'Academic'), ('hifz', 'Hifz Completion'), ('competition', 'Competition')], default='academic', max_length=20),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='category',
            field=models.CharField(choices=[('campus', 'Campus'), ('classroom', 'Classroom'), ('events', 'Events'), ('graduation', 'Graduation')], default='campus', max_length=20),
        ),
        migrations.AddField(
            model_name='program',
            name='curriculum',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='program',
            name='faq',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='program',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='program',
            name='gallery',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='program',
            name='image',
            field=models.ImageField(blank=True, help_text='Program hero image', null=True, upload_to='programs/'),
        ),
        migrations.AddField(
            model_name='program',
            name='outcomes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='program',
            name='subtitle',
            field=models.CharField(blank=True, help_text="e.g., Da'wa Dars Program", max_length=200),
        ),
    ]
