# Generated by Django 5.1.6 on 2026-03-04 17:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_category_and_program_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(help_text='WhatsApp phone number with country code (e.g., +91xxxxxxxxxx)', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('admission_message_template', models.TextField(default='🎓 *New Admission Application*\n\n━━━━━━━━━━━━━━━━━━━━\n📋 *Application Details:*\n• Name: {student_name}\n• Program: {program_name}\n• Class: {standard}\n• Phone: {phone}\n━━━━━━━━━━━━━━━━━━━━\n🏫 *Guardian Info:*\n• Name: {guardian_name}\n• Relation: {guardian_relation}\n• Phone: {guardian_phone}\n━━━━━━━━━━━━━━━━━━━━\n✨ *Zainussunna Academy*\nExcellence in Islamic Education', help_text='Message template with placeholders: {student_name}, {program_name}, {standard}, {phone}, {guardian_name}, {guardian_relation}, {guardian_phone}')),
                ('success_message_template', models.TextField(default='✅ *Admission Submitted Successfully!*\n\n🕌 *Zainussunna Academy*\n\nDear {student_name},\n\n🎉 Your application for *{program_name}* has been submitted successfully!\n\n📝 *Application Number:* {application_number}\n\nOur team will contact you shortly. Please keep your phone number ready.\n\n✨ *JazakAllah Khair* for choosing Zainussunna Academy!', help_text='Success message sent to student/guardian')),
                ('notify_on_submission', models.BooleanField(default=True)),
                ('send_confirmation', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'WhatsApp Configuration',
                'verbose_name_plural': 'WhatsApp Configuration',
            },
        ),
    ]
