# Generated by Django 5.1.6 on 2026-03-09 19:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_whatsappconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('student_photo', models.FileField(blank=True, null=True, upload_to='students/photos/')),
                ('name', models.CharField(max_length=200)),
                ('dob', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('phone_country_code', models.CharField(default='+91', max_length=5)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address_house_name', models.CharField(blank=True, max_length=200)),
                ('address_place', models.CharField(blank=True, max_length=200)),
                ('address_post_office', models.CharField(blank=True, max_length=200)),
                ('address_pin_code', models.CharField(blank=True, max_length=10)),
                ('address_state', models.CharField(blank=True, max_length=100)),
                ('address_district', models.CharField(blank=True, max_length=100)),
                ('guardian_name', models.CharField(blank=True, max_length=200)),
                ('guardian_relation', models.CharField(blank=True, max_length=100)),
                ('guardian_phone', models.CharField(blank=True, max_length=20)),
                ('guardian_phone_country_code', models.CharField(default='+91', max_length=5)),
                ('guardian_email', models.EmailField(blank=True, max_length=254)),
                ('guardian_occupation', models.CharField(blank=True, max_length=200)),
                ('class_assigned', models.CharField(blank=True, help_text='Class/Batch name', max_length=100)),
                ('teacher', models.CharField(blank=True, help_text='Assigned teacher', max_length=200)),
                ('languages_known', models.JSONField(blank=True, default=list)),
                ('enrollment_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('graduated', 'Graduated'), ('transferred', 'Transferred'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('internal_notes', models.TextField(blank=True)),
                ('admission', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_record', to='core.admission')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrolled_students', to='core.program')),
            ],
            options={
                'ordering': ['-enrollment_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exam_name', models.CharField(max_length=200)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('subject', models.CharField(max_length=200)),
                ('marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_marks', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('grade', models.CharField(blank=True, max_length=5)),
                ('notes', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='core.student')),
            ],
            options={
                'ordering': ['-exam_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('leave', 'On Leave'), ('late', 'Late')], default='present', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('marked_by', models.CharField(blank=True, max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='core.student')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StudentNote',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('is_visible', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['status', 'program'], name='core_studen_status_46d2cb_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['student_number'], name='core_studen_student_6bcc3a_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['student', 'exam_name'], name='core_examre_student_94cf41_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date', 'student'], name='core_attend_date_c24252_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'date')},
        ),
    ]
