# Generated by Django 5.1.6 on 2026-03-11 09:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_student_management'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='is_active',
        ),
        migrations.AddField(
            model_name='faculty',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact number', max_length=20),
        ),
        migrations.AddField(
            model_name='faculty',
            name='specialization',
            field=models.CharField(blank=True, help_text='e.g., Arabic Grammar, Fiqh, Quran', max_length=200),
        ),
        migrations.AddField(
            model_name='faculty',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.CharField(blank=True, help_text='e.g., Shareea 2025, Year 1', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='student_status',
            field=models.CharField(choices=[('studying', 'Studying'), ('completed', 'Completed'), ('dropped', 'Dropped')], default='studying', help_text='Academic status: Studying, Completed, or Dropped', max_length=20),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='qualification',
            field=models.CharField(blank=True, help_text='e.g., Alim, Hafiz', max_length=200),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='role',
            field=models.CharField(help_text='e.g., Ustadh, Teacher', max_length=200),
        ),
        migrations.CreateModel(
            name='AcademicClass',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Subject/Class name e.g., Arabic Grammar', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed')], default='ongoing', help_text='Class status: Ongoing or Completed', max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('faculty', models.ForeignKey(help_text='Faculty member teaching this class', on_delete=django.db.models.deletion.PROTECT, related_name='classes_taught', to='core.faculty')),
                ('students', models.ManyToManyField(blank=True, help_text='Students enrolled in this class', related_name='enrolled_classes', to='core.student')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
