# Generated by Django 5.1.6 on 2026-03-28 12:16

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_whatsapp_approval_rejection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('exam_date', models.DateField()),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-exam_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamMark',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('marks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('remarks', models.TextField(blank=True)),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_marks', to='core.academicclass')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark_entries', to='core.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_marks', to='core.student')),
            ],
            options={
                'ordering': ['exam__exam_date', 'academic_class__display_order', 'student__name'],
                'indexes': [models.Index(fields=['exam', 'academic_class'], name='core_examma_exam_id_3c5aab_idx'), models.Index(fields=['student', 'exam'], name='core_examma_student_613f8d_idx')],
                'unique_together': {('exam', 'academic_class', 'student')},
            },
        ),
    ]
